name: serviceman
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  webview_flutter: ^4.8.0
  get: 4.6.6
  dio: ^5.0.0
  path_provider: ^2.0.10
  url_launcher: ^6.1.0
  flutter_svg: ^0.22.0
  google_fonts: ^6.2.1
  carousel_slider: ^4.0.0
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.1.0
  device_info_plus: ^9.0.0
  flutter_image_compress: ^2.3.0
  mask_text_input_formatter: ^2.9.0




  flutter: 
    sdk: flutter
  image_picker: ^1.1.2
  intl: ^0.19.0
  http: ^1.2.2
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  dots_indicator: ^3.0.0
  change_app_package_name: ^1.3.0
  firebase_app_check: ^0.3.0+3
  audioplayers: ^6.0.0
  shared_preferences: ^2.3.0
  syncfusion_flutter_pdfviewer: ^24.2.8
  permission_handler: ^11.3.1
  open_file: ^3.3.2



dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter:
  assets:
    - assets/Images/
#    - assets/Lang/
  uses-material-design: true
  generate: true