name: serviceman
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter_svg: ^0.22.0
  google_fonts: ^6.2.1
  carousel_slider: ^4.0.0
  dots_indicator: ^3.0.0
  flutter: 
    sdk: flutter
  image_picker: ^1.1.2
  intl: ^0.19.0

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter:
  assets:
    - assets/Images/
#    - assets/Lang/
  uses-material-design: true
  generate: true